### PR TITLE
Set res.sse regardless of compatibility

### PR DESCRIPTION
**Pull request by cstigler**
I don't understand line 196 of sselib.coffee. It won't set `res.sse` if `options.compatibility` is set. I'm not sure why. It's been causing issues for us where `res.sse` will sometimes be undefined.

PR removes that condition.

### CODE REVIEW

**Comment by waawal** [comment]
Hi @cstigler 
Thanks for the PR!
I will try to find time to look into it tomorrow.

**Comment by cstigler** [comment]
Thanks @waawal. In addition to this, I found that res.sse sometimes wasn't being set because it did an exact match of the Accept header (`req.headers.accept === "text/event-stream"` on line 195 of sselib.coffee), but actually the Accept header can be a comma-separated list, so it just needs to _include_ that string. I added that commit to this PR also.

**Comment by waawal** [comment]
Hi Charlie,
Thanks for your contributions!
I've given you admin access to the repository, if you hand over your email I will also grant you access to the npm-package.

I'm glad that you find sselib useful :)

**Comment by waawal** [comment]
`0.0.96` is now released on npm

**Comment by cstigler** [comment]
@waawal Thank you! That would be great. My npm email is charlie@charliestigler.com

**Comment by cstigler** [comment]
Hey @waawal I'm trying to push an extra minor compatibility change (sending the `Access-Control-Allow-Origin` header that is [needed for IE8/9 compatibility](https://github.com/Yaffle/EventSource/#server-side-nodejs)). I'm getting a "permission denied" error from GitHub, looks like I don't have permissions to the repo? Could you check on those when you get a chance? Alternatively if you'd prefer I can just submit it as another PR. Thanks!

**Comment by waawal** [comment]
Hi @cstigler 
Sorry, I forgot to add the group to the repository, it should be fixed now. I also added you to the npm-package so that you can create new releases as you see fit :)

Thanks for all the awesome contributions!

**Comment by cstigler** [comment]
@waawal thanks! working great now. I'll push that little change up on NPM too.

**Pull request merged**
